project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
search-path = ["."]
python-interpreter-path = "C:/Users/User/AppData/Local/Programs/Python/Python311/python.exe"
replace-imports-with-any = [
    "pandas",
    "sqlalchemy",
]
